services:
  midas-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: midas-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production